/**
 * How DexBot signs people in: Privy email login, and nothing stored anywhere.
 *
 * The chooser module ADR 0038 §3 asks a white-label for, shaped like
 * FrockBot's `apps/cloudflare/src/auth-package.access.ts`: exactly one value
 * import and the two names the Worker reads. DexBot's deployment profile names
 * this file as its `authPackage`, and the generated wrangler config aliases
 * `#auth-package` here.
 *
 * The sign-in script is generated by `bun run build` in this package
 * (`scripts/build-sign-in.ts`); a deploy runs that first.
 */
import type { AuthPackageBuildV1 } from "@frockbot/core/contracts";
import { privyAuthPackageBuildV1, type PrivyEnvironmentV1 } from "./index.js";
import { SIGN_IN_SCRIPT_V1 } from "./generated/sign-in-script.js";

/** What a Worker must hand the Package this build deploys. */
export type AuthPackageEnvironmentV1 = PrivyEnvironmentV1;

/** The sign-in Package this build deploys. */
export const AUTH_PACKAGE_V1: AuthPackageBuildV1<AuthPackageEnvironmentV1> =
  privyAuthPackageBuildV1(SIGN_IN_SCRIPT_V1);
