/**
 * Bundles `client/sign-in.ts` with Privy's browser SDK into
 * `src/generated/sign-in-script.ts`, which the chooser serves.
 *
 * Generated rather than tracked: it is most of a megabyte of minified SDK.
 */
import { mkdir } from "node:fs/promises";
import { join } from "node:path";

const root = join(import.meta.dir, "..");
const result = await Bun.build({
  entrypoints: [join(root, "client/sign-in.ts")],
  target: "browser",
  format: "esm",
  minify: true,
});
if (!result.success) {
  for (const log of result.logs) console.error(log);
  process.exit(1);
}
const [output] = result.outputs;
if (!output) throw new Error("the sign-in bundle produced no output");
const source = await output.text();
// The page forbids eval, so a bundle that needs it would fail only in a browser.
if (/\bnew Function\s*\(|[^\w$.]eval\s*\(/.test(source)) {
  throw new Error("the sign-in bundle uses eval, which the page's CSP forbids");
}
const hash = new Bun.CryptoHasher("sha256").update(source).digest("hex").slice(0, 16);
await mkdir(join(root, "src/generated"), { recursive: true });
await Bun.write(
  join(root, "src/generated/sign-in-script.ts"),
  `// Generated by scripts/build-sign-in.ts. Do not edit.\nimport type { SignInScriptV1 } from "../page.js";\n\nexport const SIGN_IN_SCRIPT_V1: SignInScriptV1 = {\n  hash: ${JSON.stringify(hash)},\n  source: ${JSON.stringify(source)},\n};\n`,
);
console.log(`sign-in script: ${(source.length / 1024).toFixed(0)} KiB, ${hash}`);
